-- RC-CCT-T  Base Station Installer
-- Run this once in-game on the computer with the Plethora peripheral:
--   wget run https://raw.githubusercontent.com/ob-105/RC-CCT-T/main/lua/install_base.lua

local SCRIPT_URL  = "https://raw.githubusercontent.com/ob-105/RC-CCT-T/main/lua/base_station.lua"
local SCRIPT_FILE = "rc_base.lua"
local STARTUP_FILE = "startup.lua"

-- ── Checks ────────────────────────────────────────────────────────────────────
if turtle then
    printError("This installer is for a plain computer (base station), not a turtle.")
    return
end

if not http then
    printError("HTTP is not enabled. Enable it in ComputerCraft config.")
    return
end

-- ── Check for Plethora peripheral ─────────────────────────────────────────────
term.setTextColor(colors.cyan)
print("RC-CCT-T Base Station Installer")
term.setTextColor(colors.white)

local foundModule = false
local sides = {"top", "bottom", "left", "right", "front", "back"}
for _, side in ipairs(sides) do
    local ok, mods = pcall(peripheral.call, side, "listModules")
    if ok and type(mods) == "table" then
        term.setTextColor(colors.green)
        print("Found module container on: " .. side)
        print("Modules: " .. textutils.serialize(mods))
        term.setTextColor(colors.white)
        foundModule = true
        break
    end
end

-- Also check networked peripherals
if not foundModule then
    for _, name in ipairs(peripheral.getNames()) do
        local ok, mods = pcall(peripheral.call, name, "listModules")
        if ok and type(mods) == "table" then
            term.setTextColor(colors.green)
            print("Found module container: " .. name)
            print("Modules: " .. textutils.serialize(mods))
            term.setTextColor(colors.white)
            foundModule = true
            break
        end
    end
end

if not foundModule then
    term.setTextColor(colors.yellow)
    print("Warning: no Plethora module container detected.")
    print("Continuing anyway — attach the peripheral before running.")
    term.setTextColor(colors.white)
end

-- ── Download main script ──────────────────────────────────────────────────────
print("Downloading " .. SCRIPT_FILE .. "...")
local ok = shell.run("wget", SCRIPT_URL, SCRIPT_FILE)
if not ok then
    printError("Download failed. Check your internet/HTTP config.")
    return
end
print("Downloaded OK.")

-- ── Write startup.lua ─────────────────────────────────────────────────────────
if fs.exists(STARTUP_FILE) then
    term.setTextColor(colors.yellow)
    print("Warning: existing " .. STARTUP_FILE .. " will be overwritten.")
    term.setTextColor(colors.white)
    print("Press Enter to continue or Ctrl+T to abort.")
    read()
end

local f = fs.open(STARTUP_FILE, "w")
f.writeLine('-- Auto-generated by RC-CCT-T installer')
f.writeLine('shell.run("' .. SCRIPT_FILE .. '")')
f.close()

-- ── Done ──────────────────────────────────────────────────────────────────────
term.setTextColor(colors.green)
print("Installed! The base station will run RC-CCT-T automatically on every boot.")
term.setTextColor(colors.white)
print("Rebooting in 3 seconds...")
sleep(3)
os.reboot()
