-- RC-CCT-T  Turtle Installer
-- Run this once in-game:
--   wget run https://raw.githubusercontent.com/ob-105/RC-CCT-T/main/lua/install_turtle.lua

local SCRIPT_URL = "https://raw.githubusercontent.com/ob-105/RC-CCT-T/main/lua/turtle.lua"
local SCRIPT_FILE = "rc_turtle.lua"
local STARTUP_FILE = "startup.lua"

-- ── Checks ────────────────────────────────────────────────────────────────────
if not turtle then
    printError("This installer must be run on a turtle, not a plain computer.")
    return
end

if not http then
    printError("HTTP is not enabled. Enable it in ComputerCraft config.")
    return
end

-- ── Download main script ──────────────────────────────────────────────────────
term.setTextColor(colors.cyan)
print("RC-CCT-T Turtle Installer")
term.setTextColor(colors.white)

print("Downloading " .. SCRIPT_FILE .. "...")
local ok = shell.run("wget", SCRIPT_URL, SCRIPT_FILE)
if not ok then
    printError("Download failed. Check your internet/HTTP config.")
    return
end
print("Downloaded OK.")

-- ── Write startup.lua ─────────────────────────────────────────────────────────
-- Warn if a startup already exists so the user can back it up first
if fs.exists(STARTUP_FILE) then
    term.setTextColor(colors.yellow)
    print("Warning: existing " .. STARTUP_FILE .. " will be overwritten.")
    term.setTextColor(colors.white)
    print("Press Enter to continue or Ctrl+T to abort.")
    read()
end

local f = fs.open(STARTUP_FILE, "w")
f.writeLine('-- Auto-generated by RC-CCT-T installer')
f.writeLine('shell.run("' .. SCRIPT_FILE .. '")')
f.close()

-- ── Done ──────────────────────────────────────────────────────────────────────
term.setTextColor(colors.green)
print("Installed! The turtle will run RC-CCT-T automatically on every boot.")
term.setTextColor(colors.white)
print("Rebooting in 3 seconds...")
sleep(3)
os.reboot()
